run:
  issues-exit-code: 1
  build-tags:
    - e2e
  skip-dirs:
    - vendor
linters-settings:
  errcheck:
    exclude: .errcheck.txt
  staticcheck:
    checks:
      - '-SA1019' # ignore ClusterTask warning
linters:
  enable:
  - errcheck
  - gofmt
  - goimports
  - gosec
  - gocritic
  - revive
  - misspell
  - unused
